FROM apache/airflow:2.8.1

RUN pip install --no-cache-dir \
    multitasking==0.0.11 \
    yfinance==0.2.36 \
    boto3==1.34.0 \
    apache-airflow-providers-snowflake==5.1.0 \
    pandas==2.0.3 \
    dbt-core==1.7.0 \
    dbt-snowflake==1.7.0